from django.urls import path

from .views import (
    ActivityFeedView,
    ApplySavedViewView,
    CreateSavedViewView,
    CreateDatabaseView,
    CustomFieldDefinitionCreateView,
    CustomFieldDefinitionDeleteView,
    CustomFieldDefinitionListView,
    CustomFieldDefinitionUpdateView,
    DashboardView,
    DeleteSavedViewView,
    DeleteStrainAttachmentView,
    DatabaseMembersView,
    DatabaseMembershipRemoveView,
    DatabaseMembershipUpdateRoleView,
    DatabaseTransferOwnershipView,
    FileDetailView,
    LocationDetailView,
    OrganismDetailView,
    OrganizationCreateView,
    OrganizationListView,
    OrganizationMembersView,
    OrganizationExportView,
    OrganizationRestoreView,
    OrganizationSwitchView,
    PlasmidDetailView,
    SearchResultsView,
    SelectDatabaseView,
    UpdateSavedViewView,
    StrainCreateView,
    BulkEditStrainsView,
    CSVUploadView,
    StrainAttachmentDownloadView,
    ArchiveStrainView,
    ArchivedStrainListView,
    StrainDetailView,
    StrainHistoryView,
    UploadStrainAttachmentView,
    StrainListView,
    StrainUpdateView,
    StrainVersionDetailView,
    RestoreStrainView,
    RestoreVersionView,
    HardDeleteStrainView,
    SwitchDatabaseView,
    switch_database,
    toggle_theme,
)

urlpatterns = [
    path('organizations/', OrganizationListView.as_view(), name='organization-list'),
    path('organizations/create/', OrganizationCreateView.as_view(), name='organization-create'),
    path('organizations/switch/', OrganizationSwitchView.as_view(), name='organization-switch'),
    path('organizations/switch/<int:organization_id>/', OrganizationSwitchView.as_view(), name='organization-switch-id'),
    path('organizations/members/', OrganizationMembersView.as_view(), name='organization-members'),
    path('organizations/<uuid:org_id>/export/', OrganizationExportView.as_view(), name='organization-export'),
    path('organizations/<uuid:org_id>/restore/', OrganizationRestoreView.as_view(), name='organization-restore'),
    path('databases/create/', CreateDatabaseView.as_view(), name='database-create'),
    path('databases/select/', SelectDatabaseView.as_view(), name='database-select'),
    path('databases/switch/', SwitchDatabaseView.as_view(), name='database-switch'),
    path('databases/switch/<int:database_id>/', SwitchDatabaseView.as_view(), name='database-switch-id'),
    path('switch-database/<int:database_id>/', switch_database, name='switch_database'),
    path('databases/memberships/', DatabaseMembersView.as_view(), name='membership-list'),
    path(
        'databases/memberships/<int:membership_id>/role/',
        DatabaseMembershipUpdateRoleView.as_view(),
        name='membership-update-role',
    ),
    path(
        'databases/memberships/<int:membership_id>/remove/',
        DatabaseMembershipRemoveView.as_view(),
        name='membership-remove',
    ),
    path(
        'databases/memberships/<int:membership_id>/transfer-ownership/',
        DatabaseTransferOwnershipView.as_view(),
        name='membership-transfer-ownership',
    ),
    path('custom-fields/', CustomFieldDefinitionListView.as_view(), name='custom-field-definition-list'),
    path('custom-fields/create/', CustomFieldDefinitionCreateView.as_view(), name='custom-field-definition-create'),
    path('custom-fields/<int:pk>/update/', CustomFieldDefinitionUpdateView.as_view(), name='custom-field-definition-update'),
    path('custom-fields/<int:pk>/delete/', CustomFieldDefinitionDeleteView.as_view(), name='custom-field-definition-delete'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('toggle-theme/', toggle_theme, name='toggle-theme'),
    path('activity/', ActivityFeedView.as_view(), name='activity-feed'),
    path('search/', SearchResultsView.as_view(), name='search-results'),
    path('saved-views/create/', CreateSavedViewView.as_view(), name='saved-view-create'),
    path('saved-views/<int:pk>/update/', UpdateSavedViewView.as_view(), name='saved-view-update'),
    path('saved-views/<int:pk>/delete/', DeleteSavedViewView.as_view(), name='saved-view-delete'),
    path('saved-views/<int:pk>/apply/', ApplySavedViewView.as_view(), name='saved-view-apply'),
    path('strains/', StrainListView.as_view(), name='strain-list'),
    path('strains/archived/', ArchivedStrainListView.as_view(), name='strain-archived-list'),
    path('import/', CSVUploadView.as_view(), name='csv_upload'),
    path('strains/create/', StrainCreateView.as_view(), name='strain-create'),
    path('strains/bulk-edit/', BulkEditStrainsView.as_view(), name='strain-bulk-edit'),
    path('strains/<int:pk>/', StrainDetailView.as_view(), name='strain-detail'),
    path('strains/<int:pk>/update/', StrainUpdateView.as_view(), name='strain-update'),
    path('strains/<int:pk>/archive/', ArchiveStrainView.as_view(), name='strain-archive'),
    path('strains/<int:pk>/restore/', RestoreStrainView.as_view(), name='strain-restore'),
    path('strains/<int:pk>/hard-delete/', HardDeleteStrainView.as_view(), name='strain-hard-delete'),
    path('strains/<int:pk>/attachments/upload/', UploadStrainAttachmentView.as_view(), name='strain-attachment-upload'),
    path(
        'strains/<int:pk>/attachments/<int:attachment_pk>/delete/',
        DeleteStrainAttachmentView.as_view(),
        name='strain-attachment-delete',
    ),
    path(
        'strains/<int:pk>/attachments/<int:attachment_pk>/download/',
        StrainAttachmentDownloadView.as_view(),
        name='strain-attachment-download',
    ),
    path('strains/<int:pk>/history/', StrainHistoryView.as_view(), name='strain-history'),
    path('strains/<int:pk>/history/<int:version_pk>/', StrainVersionDetailView.as_view(), name='strain-version-detail'),
    path('strains/<int:pk>/history/<int:version_pk>/restore/', RestoreVersionView.as_view(), name='strain-version-restore'),
    path('organisms/<int:pk>/', OrganismDetailView.as_view(), name='organism-detail'),
    path('plasmids/<int:pk>/', PlasmidDetailView.as_view(), name='plasmid-detail'),
    path('locations/<int:pk>/', LocationDetailView.as_view(), name='location-detail'),
    path('files/<int:pk>/', FileDetailView.as_view(), name='file-detail'),
]
