from django.urls import path

from .views import (
    ActivityFeedView,
    ApplySavedViewView,
    CreateSavedViewView,
    CreateDatabaseView,
    CustomFieldDefinitionCreateView,
    CustomFieldDefinitionDeleteView,
    CustomFieldDefinitionListView,
    CustomFieldDefinitionUpdateView,
    DashboardView,
    DeleteSavedViewView,
    DatabaseMembersView,
    DatabaseMembershipRemoveView,
    DatabaseMembershipUpdateRoleView,
    DatabaseTransferOwnershipView,
    FileDetailView,
    LocationDetailView,
    OrganismDetailView,
    PlasmidDetailView,
    SearchResultsView,
    SelectDatabaseView,
    UpdateSavedViewView,
    StrainCreateView,
    BulkEditStrainsView,
    StrainDeleteView,
    StrainDetailView,
    StrainListView,
    StrainUpdateView,
    SwitchDatabaseView,
    switch_database,
)

urlpatterns = [
    path('databases/create/', CreateDatabaseView.as_view(), name='database-create'),
    path('databases/select/', SelectDatabaseView.as_view(), name='database-select'),
    path('databases/switch/', SwitchDatabaseView.as_view(), name='database-switch'),
    path('databases/switch/<int:database_id>/', SwitchDatabaseView.as_view(), name='database-switch-id'),
    path('switch-database/<int:database_id>/', switch_database, name='switch_database'),
    path('databases/memberships/', DatabaseMembersView.as_view(), name='membership-list'),
    path(
        'databases/memberships/<int:membership_id>/role/',
        DatabaseMembershipUpdateRoleView.as_view(),
        name='membership-update-role',
    ),
    path(
        'databases/memberships/<int:membership_id>/remove/',
        DatabaseMembershipRemoveView.as_view(),
        name='membership-remove',
    ),
    path(
        'databases/memberships/<int:membership_id>/transfer-ownership/',
        DatabaseTransferOwnershipView.as_view(),
        name='membership-transfer-ownership',
    ),
    path('custom-fields/', CustomFieldDefinitionListView.as_view(), name='custom-field-definition-list'),
    path('custom-fields/create/', CustomFieldDefinitionCreateView.as_view(), name='custom-field-definition-create'),
    path('custom-fields/<int:pk>/update/', CustomFieldDefinitionUpdateView.as_view(), name='custom-field-definition-update'),
    path('custom-fields/<int:pk>/delete/', CustomFieldDefinitionDeleteView.as_view(), name='custom-field-definition-delete'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('activity/', ActivityFeedView.as_view(), name='activity-feed'),
    path('search/', SearchResultsView.as_view(), name='search-results'),
    path('saved-views/create/', CreateSavedViewView.as_view(), name='saved-view-create'),
    path('saved-views/<int:pk>/update/', UpdateSavedViewView.as_view(), name='saved-view-update'),
    path('saved-views/<int:pk>/delete/', DeleteSavedViewView.as_view(), name='saved-view-delete'),
    path('saved-views/<int:pk>/apply/', ApplySavedViewView.as_view(), name='saved-view-apply'),
    path('strains/', StrainListView.as_view(), name='strain-list'),
    path('strains/create/', StrainCreateView.as_view(), name='strain-create'),
    path('strains/bulk-edit/', BulkEditStrainsView.as_view(), name='strain-bulk-edit'),
    path('strains/<int:pk>/', StrainDetailView.as_view(), name='strain-detail'),
    path('strains/<int:pk>/update/', StrainUpdateView.as_view(), name='strain-update'),
    path('strains/<int:pk>/delete/', StrainDeleteView.as_view(), name='strain-delete'),
    path('organisms/<int:pk>/', OrganismDetailView.as_view(), name='organism-detail'),
    path('plasmids/<int:pk>/', PlasmidDetailView.as_view(), name='plasmid-detail'),
    path('locations/<int:pk>/', LocationDetailView.as_view(), name='location-detail'),
    path('files/<int:pk>/', FileDetailView.as_view(), name='file-detail'),
]
