# Generated by Django 5.2.11 on 2026-02-16 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_research_database_isolation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["research_database", "file"],
                name="research_fi_researc_1023b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="strain",
            index=models.Index(
                fields=["research_database", "name"],
                name="research_st_researc_972ae7_idx",
            ),
        ),
    ]
