# Generated by Django 5.2.11 on 2026-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_file_research_fi_researc_1023b6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
