# Generated by Django 5.2.11 on 2026-02-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_customfielddefinition_customfieldvalue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("model_name", models.CharField(db_index=True, max_length=120)),
                ("object_id", models.CharField(db_index=True, max_length=120)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField()),
                (
                    "research_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="research.researchdatabase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["research_database", "timestamp"],
                        name="research_ac_researc_5f5ce9_idx",
                    ),
                    models.Index(
                        fields=["research_database", "model_name", "action"],
                        name="research_ac_researc_183281_idx",
                    ),
                ],
            },
        ),
    ]
