# Generated by Django 5.2.11 on 2026-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databasemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                default="viewer",
                max_length=20,
            ),
        ),
    ]
