# Generated by Django 5.2.11 on 2026-02-16 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_assign_database_owners"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("filter_definition", models.JSONField()),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="research.researchdatabase",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["research_database", "is_shared"],
                        name="research_sa_researc_76d387_idx",
                    ),
                    models.Index(
                        fields=["research_database", "created_by"],
                        name="research_sa_researc_d4b397_idx",
                    ),
                    models.Index(
                        fields=["research_database", "created_at"],
                        name="research_sa_researc_2e64bd_idx",
                    ),
                ],
                "unique_together": {("research_database", "name", "created_by")},
            },
        ),
    ]
