# Generated by Django 5.2.11 on 2026-02-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_savedview"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
