# Generated by Django 5.2.11 on 2026-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_strain_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="strain",
            name="selective_marker",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
