# Generated by Django 5.2.11 on 2026-02-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_strain_comments_strain_selective_marker"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
