# Generated by Django 5.2.11 on 2026-02-17 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0015_strain_archived_at_strain_archived_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="record_id",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="record_type",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="database",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="research.researchdatabase",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["database", "timestamp"], name="research_au_databas_cf67b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["database", "action"], name="research_au_databas_4aa2fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["database", "object_type", "object_id"],
                name="research_au_databas_d61514_idx",
            ),
        ),
    ]
