# Generated by Django 5.2.11 on 2026-02-17 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def seed_default_organization(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    Organization = apps.get_model('research', 'Organization')
    ResearchDatabase = apps.get_model('research', 'ResearchDatabase')
    OrganizationMembership = apps.get_model('research', 'OrganizationMembership')

    first_user = User.objects.order_by('id').first()
    if first_user is None:
        return

    base_slug = 'default-organization'
    slug = base_slug
    index = 1
    while Organization.objects.filter(slug=slug).exists():
        index += 1
        slug = f'{base_slug}-{index}'

    organization = Organization.objects.create(
        name='Default Organization',
        slug=slugify(slug),
        created_by=first_user,
    )

    user_ids = set(ResearchDatabase.objects.exclude(created_by=None).values_list('created_by_id', flat=True))
    user_ids.update(
        apps.get_model('research', 'DatabaseMembership').objects.values_list('user_id', flat=True)
    )

    for user_id in user_ids:
        role = 'admin' if user_id == first_user.id else 'member'
        OrganizationMembership.objects.get_or_create(
            user_id=user_id,
            organization=organization,
            defaults={'role': role},
        )

    ResearchDatabase.objects.filter(organization__isnull=True).update(organization=organization)


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_remove_auditlog_record_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='researchdatabase',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='research.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='research.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name', 'user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='research_or_slug_c4efc7_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='research_or_created_cce6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='research_or_organiz_69f6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'organization'], name='research_or_user_id_6f642a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
        migrations.RunPython(seed_default_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='researchdatabase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='research.organization'),
        ),
    ]
