# Generated by Django 5.2.11 on 2026-02-17 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("research", "0019_organization_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldVisibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="customfielddefinition",
            options={"ordering": ["order", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="customfieldvalue",
            name="research_cu_field_d_fbf0f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="customfieldvalue",
            name="research_cu_field_d_10947f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="customfielddefinition",
            unique_together={("research_database", "name")},
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="conditional_logic",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="default_value",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="editable_to_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="help_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="is_unique",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="key",
            field=models.SlugField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_definitions",
                to="research.organization",
            ),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="related_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organism", "Organism"),
                    ("plasmid", "Plasmid"),
                    ("location", "Location"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="validation_rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="visible_to_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_decimal",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_file",
            field=models.FileField(
                blank=True, null=True, upload_to="custom_field_files/"
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_fk_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_fk_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_integer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_long_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_multi_select",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_single_select",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="choices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("long_text", "Long text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("single_select", "Single select"),
                    ("multi_select", "Multi select"),
                    ("foreign_key", "Foreign key"),
                    ("file", "File"),
                    ("url", "URL"),
                    ("email", "Email"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfielddefinition",
            unique_together={
                ("research_database", "key"),
                ("research_database", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["field_definition", "value_single_select"],
                name="research_cu_field_d_4d0101_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["field_definition", "value_integer"],
                name="research_cu_field_d_82fb6e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["value_fk_content_type", "value_fk_object_id"],
                name="research_cu_value_f_b4fd84_idx",
            ),
        ),
        migrations.AddField(
            model_name="customfieldgroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_custom_field_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customfieldgroup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_groups",
                to="research.organization",
            ),
        ),
        migrations.AddField(
            model_name="customfieldgroup",
            name="research_database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_groups",
                to="research.researchdatabase",
            ),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fields",
                to="research.customfieldgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="customfielddefinition",
            index=models.Index(
                fields=["research_database", "order"],
                name="research_cu_researc_22431c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfielddefinition",
            index=models.Index(
                fields=["organization", "research_database"],
                name="research_cu_organiz_fe3aea_idx",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvisibilityrule",
            name="field_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_rules",
                to="research.customfielddefinition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfieldgroup",
            unique_together={("research_database", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="customfieldvisibilityrule",
            unique_together={("field_definition", "role")},
        ),
    ]
