# Generated by Django 5.2.11 on 2026-02-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0020_customfieldgroup_customfieldvisibilityrule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("dark", "Dark")], default="dark", max_length=10
            ),
        ),
    ]
