# Generated by Django 5.2.11 on 2026-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0021_alter_userprofile_theme_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="genotype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="strain",
            name="location",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="strain",
            name="organism",
            field=models.CharField(
                choices=[
                    ("bacillus_subtilis", "Bacillus subtilis"),
                    ("e_coli", "E. coli"),
                    ("k_lactis", "K. lactis"),
                    ("s_cerevisiae", "Saccharomyces cerevisiae"),
                    ("yeast", "Yeast"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="selective_marker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amp", "AMP"),
                    ("kan", "KAN"),
                    ("chlor", "Chloramphenicol"),
                    ("ura3", "URA3"),
                    ("leu2", "LEU2"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="strain_id",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
